"""
Django settings for hospital_his project.

Generated by 'django-admin startproject' using Django 5.2.4.

For details see:
    https://docs.djangoproject.com/en/5.2/topics/settings/
    https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# -----------------------------------------------------------------------------
# BASE DIRECTORIES
# -----------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------------------------------------------------
# SECURITY SETTINGS
# -----------------------------------------------------------------------------
SECRET_KEY = 'django-insecure-y-&8cw+m8$#l&_*d*p*_*f8u=9bm@re_yl7xai3jt&nhg11qqq'  # change in production!
DEBUG = True
ALLOWED_HOSTS: list[str] = ['*']  # e.g. ['127.0.0.1', 'localhost', 'yourdomain.com']

# -----------------------------------------------------------------------------
# APPLICATIONS
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'channels',

    # Local apps
    'his',
]

# -----------------------------------------------------------------------------
# MIDDLEWARE
# -----------------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -----------------------------------------------------------------------------
# URL / WSGI / ASGI CONFIG
# -----------------------------------------------------------------------------
ROOT_URLCONF = 'hospital_his.urls'
ASGI_APPLICATION = 'hospital_his.asgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # optional, for project-wide templates
        'APP_DIRS': True,                  # must be True to find templates inside apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# -----------------------------------------------------------------------------
# AUTH / USERS
# -----------------------------------------------------------------------------
AUTH_USER_MODEL = 'his.User'

# -----------------------------------------------------------------------------
# DATABASE (PostgreSQL)
# -----------------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'HIS_db',  # your DB name inside MongoDB
        'CLIENT': {
            'host': 'mongodb+srv://aramanraj01:tNoXW7ZsLpOJCxvg@cluster0.ephjclx.mongodb.net/PrivateDB?retryWrites=true&w=majority',
            # you can also specify other options here like ssl, retryWrites, etc.
        }
    }
}


# -----------------------------------------------------------------------------
# PASSWORD VALIDATORS
# -----------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -----------------------------------------------------------------------------
# INTERNATIONALIZATION
# -----------------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -----------------------------------------------------------------------------
# STATIC / MEDIA FILES
# -----------------------------------------------------------------------------
# settings.py
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'his' / 'static',  # path to your static folder
]

# For production (optional)
STATIC_ROOT = BASE_DIR / 'staticfiles'


# -----------------------------------------------------------------------------
# DEFAULT AUTO FIELD
# -----------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------------------------------------------------------------
# REST FRAMEWORK (optional defaults)
# -----------------------------------------------------------------------------
# settings.py

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        # optionally add SessionAuthentication if you want login-based access
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
